### PR TITLE
use yarn with appveyor

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
🙏  x2

### CODE REVIEW

**Comment by amilajack** [comment]
I've been getting the appveyor error locally. Not sure why travis is passing.

**Comment by ZakariaRidouh** [comment]
@amilajack I wonder why it's throwing this error:

```
error: unknown option `--cache-min'
```

https://ci.appveyor.com/project/amilajack/popcorn-time-desktop/build/692#L871

**Comment by amilajack** [comment]
No idea :(

**Comment by amilajack** [comment]
How about this:

Let's have a single PR that adds both npm and yarn support for tests. I think that's the proper way of supporting both yarn and npm installations is by running the tests against both npm and travis.

**Pull request closed without merging**
