### PR TITLE
Release 0.0.4 alpha

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
Parallelize everything

**Comment by amilajack** [comment]
Travis builds are failing because WebChimera isn't installing on OSX for some reason:

```
> wcjs-prebuilt@3.0.0 postinstall /Users/travis/build/amilajack/popcorn-time-desktop/app/node_modules/wcjs-prebuilt
> node install.js

Fetching WebChimera prebuilt for Electron: 
WebChimera version: v0.2.6 
Electron version: v1.2.6 
Platform: osx 
Arch: x64 
Target dir: ./bin

Looking for WebChimera download at https://api.github.com/repos/RSATom/WebChimera.js/releases/tags/v0.2.6


No WebChimera release found matching your environment
npm WARN install:wcjs-prebuilt@3.0.0 wcjs-prebuilt@3.0.0 postinstall: `node install.js`
npm WARN install:wcjs-prebuilt@3.0.0 Exit status 1
PopcornTime@0.0.4 /Users/travis/build/amilajack/popcorn-time-desktop/app
└── wcjs-renderer@1.0.2 
```

**Comment by thangngoc89** [comment]
I don't have a Mac here so I can't help

**Comment by thangngoc89** [comment]
@amilajack maybe try to clean cache on Travis

**Comment by ZakariaRidouh** [comment]
I've got a mac so I can test 😄

**Pull request merged**
