### PR TITLE
Upgrade electron to ^1.3.1

### PR DESCRIPTION
**Pull request by thangngoc89**
Well there is not sound (yet). But at least there is image on Windows

### CODE REVIEW

**Comment by amilajack** [comment]
This breaks on macOS. I'll look into a solution for this/

**Comment by thangngoc89** [comment]
Thanks.

**Comment by amilajack** [comment]
Just another reason why we need to manually build electron

**Comment by ZakariaRidouh** [comment]
@amilajack WebChimra doesn't work on this version of electron right?

**Comment by amilajack** [comment]
On macOS, it doesnt

**Comment by amilajack** [comment]
@ZakariaRidouh I've updated my response in this issue: https://github.com/amilajack/popcorn-time-desktop/issues/49#issuecomment-234120650

**Pull request closed without merging**
