### PR TITLE
Use babel-preset-es2015-node6 instead of es2015

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by amilajack** [comment]
Thanks!

**Comment by thangngoc89** [comment]
Looks like I messed up something with this PR 
https://travis-ci.org/amilajack/popcorn-time-desktop/builds/146758839#L475

**Comment by amilajack** [comment]
Should we temporarily revert the changes in the release branch?

**Comment by thangngoc89** [comment]
I think we have to

See https://github.com/chentsulin/electron-react-boilerplate/issues/275

Sory for not investigating this thoroughly

**Comment by amilajack** [comment]
No worries! PR to revert?

**Comment by thangngoc89** [comment]
PR's coming

**Pull request merged**
