### PR TITLE
make clicking logo go to main screen

### PR DESCRIPTION
**Pull request by ZakariaRidouh**

### CODE REVIEW

**Comment by amilajack** [comment]
Failing because of linter errors. Try adding text editor support for eslint.

**Comment by amilajack** [comment]
You can also run `npm run lint`. Remember to scroll up for a while until you see the errors. There are hundreds of warnings so it might take some searching.

**Comment by thangngoc89** [comment]
Why dont you remove/fix those rules with warnings? It's pretty annoying.

**Comment by ZakariaRidouh** [comment]
@amilajack Yeah ill run that command from now on. I was having problems with my installation so I just committed on Github.

**Comment by ZakariaRidouh** [comment]
whoop, found the issues, about to fix the indentation 😄

**Comment by amilajack** [comment]
Temporarily removed the 'no-this' rule. That significantly reduced the linter warnings.

**Comment by amilajack** [comment]
There's one more error left. You can make it easier to find by temporarily removing 'no-this' in the eslint.

**Comment by ZakariaRidouh** [comment]
ah finally fixed 😸

**Comment by amilajack** [comment]
Failing because of a network timeout issue, which is negligible.

**Comment by amilajack** [comment]
Merged 🎆

**Pull request merged**
