### PR TITLE
Use popcorntime api v2

### PR DESCRIPTION
**Pull request by pedroabreu**

### CODE REVIEW

**Comment by pedroabreu** [comment]
For some reason it started to fail in a random test... Even the next branch, if I try to run `yarn start`, the app freezes on startup 🤔

**Comment by amilajack** [comment]
I seem to be getting this error. Are you able to reproduce this?:

Screen Shot 2019-04-22 at 11 58 19 AM

**Comment by pedroabreu** [comment]
When you select an episode, it throws that error because `getShowData` is called with type `episode`, which is not defined in the switch case.

**Comment by pedroabreu** [comment]
This is related to some stuff I deleted from the state in a Item refactor. The `episode` state is not used anywhere (hence I deleted it).

It's hard to understand the item component as there's a bunch of stuff happening there that can be split between movies and shows. I'm planning on having a look at that at some point

**Comment by amilajack** [comment]
Yea its definitely one of the things I would very much like to refactor along with the `Home` component. 

Were you able to get the show torrents working with this PR?

**Comment by pedroabreu** [comment]
Not really, not even running the tests on the master or next branch solves it. Not really sure what's going on, need to investigate a bit more

**Comment by amilajack** [comment]
Do you get any stack traces from running `yarn start`? Also any stack traces from `yarn dev`?

**Comment by pedroabreu** [comment]
No stack trace on `yarn start`. Was now trying to open/load devtools in the production build but no luck

**Comment by amilajack** [comment]
that can be done by running `DEBUG_PROD=true yarn package`. This project is based off of [electron-react-boilerplate ](https://github.com/electron-react-boilerplate/electron-react-boilerplate). Here's the [docs for the packaging](https://electron-react-boilerplate.js.org/docs/packaging#building-to-multiple-platforms).

**Comment by pedroabreu** [comment]
Interesting, so this is definitely because of the `getShowData` issue. I'll bring it back (and ignore the lint issues)

**Pull request closed without merging**
