### PR TITLE
BackButton, Poster and Similar component

### PR DESCRIPTION
**Pull request by pedroabreu**
Make 3 new components from the item component, moving similar logic to it's own component. A first step into breaking up the item page into smaller pieces.

PS: Can you make the `next` branch the default repo branch ? Makes it easier to open PRs as now it's always pointing to the `master` branch when you open a new one

### CODE REVIEW

**Comment by amilajack** [comment]
Interesting how the tests are only passing on windows. What machine are you using locally? Do the tests work for you locally?

**Comment by pedroabreu** [comment]
Using a mac. And the download torrent tests never pass on my local. All the other do though...

**Comment by amilajack** [comment]
I'll try to see if I can get the tests passing for this.

**Comment by amilajack** [comment]
Is the movie playback working for you? If it is but the only thing that isn't working is the tests then we can merge into next and fix the tests later

**Pull request merged**
