### PR TITLE
[WIP] Test with macOS on Travis CI

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by amilajack** [comment]
@thangngoc89 this is a great PR! Wanted to add this for a long time. Really appreciate it.

One thing I should mention:


`npm run test` runs all the tests by default (pakage, lint, etc). `npm run test-api` will the butter api. This will fail on linux because `WebChimera` cannot be installed on linux. I think we should change the condition to something like:

```
script:
    - npm run build
    - npm run package
   # Cannot run until WebChimera support comes to Linux
   - if [ $TRAVIS_OS_NAME == "osx" ]; then
       npm run test-api
     fi
    - npm run test-e2e
    - npm run lint
```

**Comment by thangngoc89** [comment]
OK. I'm waiting for feedback on Travis and make those changes

**Comment by amilajack** [comment]
Also the tests are failing because of something I did. I made breaking changes in my `kat-api` github repo. This is fixed in a commit that I am about to push.

**Comment by thangngoc89** [comment]
Please ping me when you pushed it. The test should not fail on Linux

**Comment by thangngoc89** [comment]
@amilajack I'm done with basic configuration, test on macOS fails and I don't have access to a Mac so I can't test it. Could you do the rest ?

**Comment by thangngoc89** [comment]
Also, please squash this branch before merging. It's like a mess

**Comment by amilajack** [comment]
Hmm. try merging with the release branch and pushing again. I think that should resolve all or most of the issues

**Comment by thangngoc89** [comment]
What about this 

https://travis-ci.org/amilajack/popcorn-time-desktop/jobs/146764422#L2415

Also, there is no `npm run test-api`

**Comment by amilajack** [comment]
npm run test-api should be added in the commits i pushed

**Pull request closed without merging**
