### PR TITLE
Remove gulp, use webpack for sass compilation

### PR DESCRIPTION
**Pull request by thangngoc89**
Webpack is too smart, it parses font require hooks in SASS files so it creates some duplicated font files in dist folder.

### CODE REVIEW

**Comment by amilajack** [comment]
Wow! This is really great! One comment: I think we should update the chrome version to >=50.

Also it would be really nice if we could add screenshot testing. Probably in another PR.

**Comment by thangngoc89** [comment]
PR updated. 

> Also it would be really nice if we could add screenshot testing. Probably in another PR.

Sorry, I have no experience with this one

**Comment by thangngoc89** [comment]
cssnano is not needed since css-loader included it by default.

**Comment by amilajack** [comment]
Thanks again!

**Pull request merged**
