### PR TITLE
Run build on macOS with TravisCI

### PR DESCRIPTION
**Pull request by thangngoc89**
I messed up with the previous PR. (#60)

### CODE REVIEW

**Comment by thangngoc89** [comment]
@amilajack lint step is failing

**Comment by amilajack** [comment]
Yea, my bad. I screwed up my rebase. I'm fixing that in another branch so i can merge into the release branch. Then you should be able to merge without a problem

**Comment by thangngoc89** [comment]
Rebased this branch

**Comment by amilajack** [comment]
Bam! Travis OSX support! Thanks for these killer PR's!

**Pull request merged**
