### PR TITLE
update electron

### PR DESCRIPTION
**Pull request by ZakariaRidouh**

### CODE REVIEW

**Comment by amilajack** [comment]
The current semvar allows the latest minor and patch versions to be installed.

https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers

Try running `npm update` and you will update all local deps to latest patch/minor

**Comment by ZakariaRidouh** [comment]
In accordance to [this]( https://github.com/electron/electron/blob/master/docs/tutorial/electron-versioning.md), its better to control exactly what version of electron your using.

 https://github.com/electron/electron/blob/master/docs/tutorial/electron-versioning.md

`If you are using electron or electron-prebuilt, we recommend that you set a fixed version number (1.1.0 instead of ^1.1.0) to ensure that all upgrades of Electron are a manual operation made by you, the developer.`

**Comment by amilajack** [comment]
I see. Makes sense.

**Comment by amilajack** [comment]
Thanks!

**Comment by ZakariaRidouh** [comment]
:smile:!

**Pull request merged**
